import "@/styles/globals.css";
import Header from "@/components/Header";

import { Roboto } from "next/font/google";
export const roboto = Roboto({
  subsets: ["latin"],
});

export const metadata = {
  title: {
    template: "%s | Blog Application",
    default: "Home | Blog Application",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.className}`} suppressHydrationWarning>
      <body>
        <section className="container">
          <header className="flex justify-between p-8 pt-2 pb-2 text-right shadow-md border-b-1 dark:border-b-0 ">
            <Header />
          </header>
          {children}
        </section>
      </body>
    </html>
  );
}
